apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: dtaber
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-deployment
        image: harbor.dev.afsmtddso.com/dtaber-harbor-project/db:49d0fd3-c4d9936
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: db-secret
